apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: crossplane-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVVYRVlDTk1STkxOQ1FBMlg=
  AWS_SECRET_ACCESS_KEY: UE1yaFJIVEgzRDNRcTRwYmpmY2tVZkhTQ2s0V0ZMa1JablBUVHYwMg==
