apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-management
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yohanan91/Helm.git
    targetRevision: main
    path: aws-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true