apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: example-bucket
spec:
  forProvider:
    acl: private
    locationConstraint: us-east-1
  providerConfigRef:
    name: aws-provider